_target_: torchvision.transforms.v2.Compose
transforms:
  - _target_: torchvision.transforms.v2.PILToTensor
  - _target_: torchvision.transforms.v2.ToDtype
    dtype:
      _target_: src.utils.utils.get_float32
    scale: True
  - _target_: torchvision.transforms.v2.Resize
    size: 230
  - _target_: torchvision.transforms.v2.CenterCrop
    size: 224
  - _target_: torchvision.transforms.v2.Normalize
    mean: [0.1, 0.1, 0.1]
    std: [0.2, 0.2, 0.2]